#include "Waterchip.h"

/*
    Verify that we can test Waterchip, itself.
*/

import variable test_Example_Waterchip_CanTestWaterchip;

describe("Waterchip - Can test other Waterchip tests") begin

    debug_msg("Waterchip = PRINT HERE");

    variable test_data = test_Example_Waterchip_CanTestWaterchip;

    it("can get exported test suite details") begin
        print("HI FROM TEST, the data: " + test_Example_Waterchip_CanTestWaterchip);
    end
end
