#include "Waterchip/TestHelper.h"

import_test_data(WaterchipTestExamples_RunningTests_UsingCoreMacros)
import_test_data(WaterchipTestExamples_RunningTests_UsingCoreMacros_OutputData)

describe("Running a basic Waterchip test") begin

    variable test_data = WaterchipTestExamples_RunningTests_UsingCoreMacros;
    variable test_output_data = WaterchipTestExamples_RunningTests_UsingCoreMacros_OutputData;
    variable test_suites = test_data.test_suites;

    it("runs the expected test but no others") begin
        expect(test_output_data.ran_the_wrong_test) to_be_false;
        expect(test_output_data.ran_the_right_test) to_equal("ran the RIGHT test");
        expect(test_output_data) to_have_length(1);
    end
end
