#include "Waterchip_v2.h"

export variable WaterchipTestExamples_UsingCoreMacros;
export variable WaterchipTestExamples_UsingCoreMacros_OutputData;

variable output_data;

define_tests_proc(has_no_tests) begin
    // No tests
end

define_tests_proc(has_two_todo_tests) begin
    define_skipped_test_without_body("I am a todo without body!");
    define_skipped_test("I am a todo!") begin
        // This should not run!
    end
end

define_tests_proc(normal_tests) begin
    define_test("this is a test") begin
        output_data.ran_test = true; // verify that this does not run!
    end
    define_test("this is another test") begin
        output_data.ran_another_test = true; // verify that this does not run!
    end
end

procedure start begin
    // Setup data which can be read from these tests' tests for verification
    output_data = {};
    fix_array(output_data);
    WaterchipTestExamples_UsingCoreMacros_OutputData = output_data;

    invoke_define_tests_proc("Empty describe", has_no_tests, false);
    invoke_define_tests_proc("Skipped tests", has_two_todo_tests, false);
    invoke_define_tests_proc("Normal tests", normal_tests, false);

    WaterchipTestExamples_UsingCoreMacros = __waterchip_data;
end
