#define DEBUG_NAME "ExampleSpec"
#include "FormattedDebug.h"
/////////////////////////////

#include "Waterchip.h"

describe("some test suite") begin

    setup begin
        // debug("SETUP");
    end

    test("this test") begin
        expect(69) to_equal(420);
    end

    test("another test") begin
        expect(69) to_equal(69);
    end

    teardown begin
        // debug("TEARDOWN");
    end
    
end
